# Generated by Django 4.2.8 on 2024-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="choise_1",
            new_name="choice_1",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="choise_2",
            new_name="choice_2",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="choise_3",
            new_name="choice_3",
        ),
        migrations.AddField(
            model_name="question",
            name="choice_4",
            field=models.CharField(default="", max_length=200),
        ),
    ]
