# Generated by Django 4.2.8 on 2024-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_rename_choise_1_question_choice_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choice_4",
            field=models.CharField(max_length=200),
        ),
    ]
