# Generated by Django 4.2.8 on 2024-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_examjson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examjson",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="examjson",
            name="question",
        ),
        migrations.AddField(
            model_name="examjson",
            name="json_data",
            field=models.JSONField(default=""),
        ),
    ]
