# Generated by Django 4.2.8 on 2024-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_remove_examjson_exam_remove_examjson_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examjson",
            name="json_data",
            field=models.JSONField(),
        ),
    ]
