# Generated by Django 4.2.8 on 2024-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="content",
            field=models.CharField(default="SOME STRING", max_length=2000),
        ),
        migrations.DeleteModel(
            name="Content",
        ),
    ]
