# Generated by Django 4.2.8 on 2024-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_chapter_name_alter_grade_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="title",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
