# Generated by Django 4.2.8 on 2024-05-18 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_chapter_id_alter_grade_id_alter_grade_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
    ]
