# Generated by Django 4.2.8 on 2024-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_chapter_id_alter_grade_id_alter_lesson_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="image",
            field=models.CharField(default="", max_length=500),
        ),
    ]
