# Generated by Django 4.2.8 on 2024-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_grade_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=3)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
