# Generated by Django 4.2.8 on 2024-06-19 15:23

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_author_json_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_file",
                    models.FileField(
                        upload_to="json_files/", validators=[books.models.validate_json]
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
