# Generated by Django 4.2.8 on 2024-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_mymodel_delete_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="image_file",
            field=models.ImageField(default="", upload_to="image_book/"),
        ),
    ]
