# Generated by Django 4.2.8 on 2024-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_mymodel_image_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mymodel",
            old_name="image_file",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="grade",
            name="image",
            field=models.ImageField(default="", upload_to="image_book/"),
        ),
    ]
