# Generated by Django 4.2.8 on 2024-06-19 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_rename_image_file_mymodel_image_alter_grade_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyModel",
            new_name="JsonBook",
        ),
    ]
