# Generated by Django 4.2.8 on 2024-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0012_rename_mymodel_jsonbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsonbook",
            name="image",
            field=models.ImageField(
                default="image_book/Lich-su-12.jpg", upload_to="image_book/"
            ),
        ),
    ]
